### ISSUE TITLE
Error after plugin installation

### ISSUE THREAD

**Issue by akatav** [ved-sharma/HyperStackReg#1]
Hi Ved
I have installed HyperStackReg into Fiji.I get the following error.
![Screenshot (8)](https://user-images.githubusercontent.com/721570/75749880-34acab00-5d66-11ea-8f93-086f9aa92b0e.png)
I have all the dependant plugins.

**Comment by garcia-nacho** [comment]
Same issue here. Did you manage to fix it?

**Comment by ved-sharma** [comment]
Coming little late to this issue... but wanted to respond in case someone else comes across a similar problem.

I think this error is related to the JAVA installation on your computer. Take a look at this post where this is discussed:
https://forum.image.sc/t/no-javac-jar-found/2340
